apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-app-helm
spec:
  template:
    spec:
      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
